// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR0M-2OQBWvMkKBPmVrb0zh9eZqEyk2Eo',
    appId: '1:358708930719:web:98e4e0fa18be021e6c9aaa',
    messagingSenderId: '358708930719',
    projectId: 'motionhack-11',
    authDomain: 'motionhack-11.firebaseapp.com',
    storageBucket: 'motionhack-11.appspot.com',
    measurementId: 'G-FD9GSMXQEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBymCgHQVx2XWvZcuIsUKLFU6vdC41l28Q',
    appId: '1:358708930719:android:a20ab450cc0be2ea6c9aaa',
    messagingSenderId: '358708930719',
    projectId: 'motionhack-11',
    storageBucket: 'motionhack-11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_ZZTaXbhKVaTyIAPQhsR7-pCfkVUtPg8',
    appId: '1:358708930719:ios:c34ab2d9270163186c9aaa',
    messagingSenderId: '358708930719',
    projectId: 'motionhack-11',
    storageBucket: 'motionhack-11.appspot.com',
    iosBundleId: 'com.example.motionhack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_ZZTaXbhKVaTyIAPQhsR7-pCfkVUtPg8',
    appId: '1:358708930719:ios:7b073fbb687d93cb6c9aaa',
    messagingSenderId: '358708930719',
    projectId: 'motionhack-11',
    storageBucket: 'motionhack-11.appspot.com',
    iosBundleId: 'com.example.motionhack.RunnerTests',
  );
}
